local P,T,U,R=game:GetService("Players"),game:GetService("TweenService"),game:GetService("UserInputService"),game:GetService("RunService")
local LP,Cam,ch,cu,hd,vi=P.LocalPlayer,workspace.CurrentCamera,{},nil,false,true
local C={Bg=Color3.fromRGB(13,14,18),Cd=Color3.fromRGB(22,24,30),Ac=Color3.fromRGB(115,87,255),Gr=Color3.fromRGB(0,220,140)}
local O={Active=false,FOV=150,Smooth=5,Lock=false,Wall=false,Switch=false,Key=Enum.KeyCode.E,ESP=false}
local Cir=Drawing.new("Circle")Cir.Color,Cir.Thickness,Cir.NumSides,Cir.Visible=C.Ac,1.5,64,false
local G=Instance.new("ScreenGui",LP:WaitForChild("PlayerGui"))G.Name,G.ResetOnSpawn="PremiumUI",false
local M=Instance.new("CanvasGroup",G)M.Size,M.Position,M.BackgroundColor3=UDim2.new(0,310,0,480),UDim2.new(0.5,-155,0.5,-240),C.Bg
Instance.new("UICorner",M).CornerRadius=UDim.new(0,10)Instance.new("UIStroke",M).Color=Color3.fromRGB(35,38,47)
local TB=Instance.new("Frame",M)TB.Size,TB.BackgroundTransparency=UDim2.new(1,0,0,40),1
local TA=Instance.new("TextButton",TB)TA.Size,TA.BackgroundTransparency,TA.Text,TA.TextColor3,TA.Font,TA.TextSize=UDim2.new(0.5,0,1,0),1,"AIMBOT",Color3.new(1,1,1),Enum.Font.GothamBold,13
local TE=Instance.new("TextButton",TB)TE.Size,TE.Position,TE.BackgroundTransparency,TE.Text,TE.TextColor3,TE.Font,TE.TextSize=UDim2.new(0.5,0,1,0),UDim2.new(0.5,0,0,0),1,"ESP VISUALS",Color3.fromRGB(140,145,160),Enum.Font.GothamBold,13
local PA=Instance.new("ScrollingFrame",M)PA.Size,PA.Position,PA.BackgroundTransparency,PA.ScrollBarThickness,PA.ScrollBarImageColor3=UDim2.new(1,0,1,-50),UDim2.new(0,0,0,45),1,2,C.Ac
local PE=Instance.new("ScrollingFrame",M)PE.Size,PE.Position,PE.BackgroundTransparency,PE.ScrollBarThickness,PE.ScrollBarImageColor3,PE.Visible=UDim2.new(1,0,1,-50),UDim2.new(0,0,0,45),1,2,C.Ac,false
local L1,L2=Instance.new("UIListLayout",PA),Instance.new("UIListLayout",PE)L1.Padding,L1.HorizontalAlignment,L2.Padding,L2.HorizontalAlignment=UDim.new(0,6),Enum.HorizontalAlignment.Center,UDim.new(0,6),Enum.HorizontalAlignment.Center
L1:GetPropertyChangedSignal("AbsoluteContentSize"):Connect(function()PA.CanvasSize=UDim2.new(0,0,0,L1.AbsoluteContentSize.Y+15)end)
L2:GetPropertyChangedSignal("AbsoluteContentSize"):Connect(function()PE.CanvasSize=UDim2.new(0,0,0,L2.AbsoluteContentSize.Y+15)end)
TA.MouseButton1Click:Connect(function()PA.Visible,PE.Visible,TA.TextColor3,TE.TextColor3=true,false,Color3.new(1,1,1),Color3.fromRGB(140,145,160)end)
TE.MouseButton1Click:Connect(function()PA.Visible,PE.Visible,TA.TextColor3,TE.TextColor3=false,true,Color3.fromRGB(140,145,160),Color3.new(1,1,1)end)
local function tg(p,t,k)
local F=Instance.new("Frame",p)F.Size,F.BackgroundColor3=UDim2.new(0,280,0,44),C.Cd Instance.new("UICorner",F).CornerRadius=UDim.new(0,6)
local L=Instance.new("TextLabel",F)L.Size,L.Position,L.BackgroundTransparency,L.Text,L.TextColor3,L.Font,L.TextSize,L.TextXAlignment=UDim2.new(0,160,1,0),UDim2.new(0,12,0,0),1,t,Color3.fromRGB(140,145,160),Enum.Font.GothamMedium,13,Enum.TextXAlignment.Left
local S=Instance.new("TextButton",F)S.Size,S.Position,S.BackgroundColor3,S.Text=UDim2.new(0,38,0,20),UDim2.new(1,-50,0.5,-10),Color3.fromRGB(40,44,54),"" Instance.new("UICorner",S).CornerRadius=UDim.new(1,0)
local D=Instance.new("Frame",S)D.Size,D.Position,D.BackgroundColor3=UDim2.new(0,14,0,14),UDim2.new(0,3,0.5,-7),Color3.fromRGB(180,185,200) Instance.new("UICorner",D).CornerRadius=UDim.new(1,0)
S.MouseButton1Click:Connect(function()O[k]=not O[k] local s=O[k]T:Create(S,TweenInfo.new(0.15),{BackgroundColor3=s and C.Gr or Color3.fromRGB(40,44,54)}):Play()T:Create(D,TweenInfo.new(0.15),{Position=s and UDim2.new(1,-17,0.5,-7) or UDim2.new(0,3,0.5,-7)}):Play()T:Create(L,TweenInfo.new(0.15),{TextColor3=s and Color3.new(1,1,1) or Color3.fromRGB(140,145,160)}):Play()end)end
local function sd(p,t,mn,mx,k)
local F=Instance.new("Frame",p)F.Size,F.BackgroundColor3=UDim2.new(0,280,0,50),C.Cd Instance.new("UICorner",F).CornerRadius=UDim.new(0,6)
local L=Instance.new("TextLabel",F)L.Size,L.Position,L.BackgroundTransparency,L.Text,L.TextColor3,L.Font,L.TextSize,L.TextXAlignment=UDim2.new(0,160,0,25),UDim2.new(0,12,0,2),1,t,Color3.new(1,1,1),Enum.Font.GothamMedium,13,Enum.TextXAlignment.Left
local V=Instance.new("TextLabel",F)V.Size,V.Position,V.BackgroundTransparency,V.Text,V.TextColor3,V.Font,V.TextSize,V.TextXAlignment=UDim2.new(0,80,0,25),UDim2.new(1,-92,0,2),1,tostring(O[k]),C.Ac,Enum.Font.GothamBold,12,Enum.TextXAlignment.Right
local B=Instance.new("TextButton",F)B.Size,B.Position,B.BackgroundColor3,B.Text=UDim2.new(0,256,0,6),UDim2.new(0.5,-128,0,34),Color3.fromRGB(40,44,54),"" Instance.new("UICorner",B).CornerRadius=UDim.new(1,0)
local Fl=Instance.new("Frame",B)Fl.Size,Fl.BackgroundColor3=UDim2.new((O[k]-mn)/(mx-mn),0,1,0),C.Ac Instance.new("UICorner",Fl).CornerRadius=UDim.new(1,0)
local m=false local function u()local pct=math.clamp((U:GetMouseLocation().X-B.AbsolutePosition.X)/B.AbsoluteSize.X,0,1)Fl.Size=UDim2.new(pct,0,1,0)local val=math.round(mn+(pct*(mx-mn)))V.Text=tostring(val)O[k]=val end
B.InputBegan:Connect(function(io)if io.UserInputType==Enum.UserInputType.MouseButton1 then m=true u() end end)U.InputChanged:Connect(function(io)if m and(io.UserInputType==Enum.UserInputType.MouseMovement or io.UserInputType==Enum.UserInputType.Touch)then u() end end)U.InputEnded:Connect(function(io)if io.UserInputType==Enum.UserInputType.MouseButton1 then m=false end end)end
tg(PA,"Toggle Button","Active")sd(PA,"FOV",10,600,"FOV")sd(PA,"Smoothness",1,20,"Smooth")tg(PA,"Target Lock","Lock")tg(PA,"Wall Check","Wall")tg(PA,"Switch Targets","Switch")tg(PE,"ESP","ESP")
local dg,is,sp TB.InputBegan:Connect(function(io)if io.UserInputType==Enum.UserInputType.MouseButton1 then dg,is,sp=true,io.Position,M.Position io.Changed:Connect(function()if io.UserInputState==Enum.UserInputState.End then dg=false end end)endend)
U.InputChanged:Connect(function(io)if dg and io.UserInputType==Enum.UserInputType.MouseMovement then local d=io.Position-is M.Position=UDim2.new(sp.X.Scale,sp.X.Offset+d.X,sp.Y.Scale,sp.Y.Offset+d.Y)endend)
U.InputBegan:Connect(function(io,p)if not p and io.KeyCode==Enum.KeyCode.RightShift then vi=not vi M.Visible=vi end end)
local function ln()local l=Drawing.new("Line")l.Thickness,l.Color,l.Visible=1,C.Ac,false return l end
local function cl(m)if ch[m] then for _,v in pairs(ch[m].Bones)do v:Remove() end for _,v in pairs(ch[m].Box)do v:Remove() end ch[m]=nil end end
local Bs={{"Head","UpperTorso"},{"UpperTorso","LowerTorso"},{"UpperTorso","LeftUpperArm"},{"LeftUpperArm","LeftLowerArm"},{"LeftLowerArm","LeftHand"},{"UpperTorso","RightUpperArm"},{"RightUpperArm","RightLowerArm"},{"RightLowerArm","RightHand"},{"LowerTorso","LeftUpperLeg"},{"LeftUpperLeg","LeftLowerLeg"},{"LowerTorso","RightUpperLeg"},{"RightUpperLeg","RightLowerLeg"},{"Torso","Head"},{"Torso","Left Arm"},{"Torso","Right Arm"},{"Torso","Left Leg"},{"Torso","Right Leg"}}
local function dE()if not O.ESP then for m,_ in pairs(ch)do cl(m) end return end
for _,o in ipairs(workspace:GetDescendants())do if o:IsA("Model")and o:FindFirstChild("Humanoid")and o~=LP.Character and o.Humanoid.Health>0 then local hr=o:FindFirstChild("HumanoidRootPart")or o:FindFirstChild("Torso")if hr then local _,os=Cam:WorldToViewportPoint(hr.Position)if os then if not ch[o] then ch[o]={Box={ln(),ln(),ln(),ln()},Bones={}}for i=1,#Bs do table.insert(ch[o].Bones,ln())end end local d,sz=ch[o],hr.Size.Y*1.2 local tp=Cam:WorldToViewportPoint(hr.Position+Vector3.new(0,sz,0))local bt=Cam:WorldToViewportPoint(hr.Position-Vector3.new(0,sz,0))if tp.Y and bt.Y then local h,w=math.abs(tp.Y-bt.Y),math.abs(tp.Y-bt.Y)*0.6 local x,y=tp.X-(w/2),tp.Y for i=1,4 do d.Box[i].Visible=true end d.Box.From,d.Box.To=Vector2.new(x,y),Vector2.new(x+w,y)d.Box.From,d.Box.To=Vector2.new(x+w,y),Vector2.new(x+w,y+h)d.Box.From,d.Box.To=Vector2.new(x+w,y+h),Vector2.new(x,y+h)d.Box.From,d.Box.To=Vector2.new(x,y+h),Vector2.new(x,y)end for i,b in ipairs(Bs)do local p1,p2=o:FindFirstChild(b),o:FindFirstChild(b)if p1 and p2 then local s1,oA=Cam:WorldToViewportPoint(p1.Position)local s2,oB=Cam:WorldToViewportPoint(p2.Position)if oA and oB then d.Bones[i].From,d.Bones[i].To,d.Bones[i].Visible=Vector2.new(s1.X,s1.Y),Vector2.new(s2.X,s2.Y),true else d.Bones[i].Visible=false end else d.Bones[i].Visible=false end end else cl(o)end end else if ch[o] then cl(o)end end end end
local function gt()if O.Lock and cu and cu.Parent and cu.Parent:FindFirstChild("Humanoid")and cu.Parent.Humanoid.Health>0 then return cu end cu=nil local cL,mD,ct=nil,O.FOV,Cam.ViewportSize/2
for _,o in ipairs(workspace:GetDescendants())do if o:IsA("Model")and o:FindFirstChild("Humanoid")and o:FindFirstChild("Head")and o~=LP.Character and o.Humanoid.Health>0 then local sp,os=Cam:WorldToViewportPoint(o.Head.Position)if os then local w=false if O.Wall then local rp=RaycastParams.new()rp.FilterType,rp.FilterDescendantsInstances=Enum.RaycastFilterType.Exclude,{LP.Character,o}if workspace:Raycast(Cam.CFrame.Position,o.Head.Position-Cam.CFrame.Position,rp)then w=true end end if not w then local d=(Vector2.new(sp.X,sp.Y)-ct).Magnitude if d<mD then mD,cL=d,o.Head end end end end end if O.Lock then cu=cL end return cL end
U.InputBegan:Connect(function(io,p)if not p and io.KeyCode==O.Key then hd=true end end)U.InputEnded:Connect(function(io)if io.KeyCode==O.Key then hd=false if not O.Lock then cu=nil end end end)R.Heartbeat:Connect(function()if O.Switch and cu and cu.Parent.Humanoid.Health <= 0 then cu=nil end end)
R.RenderStepped:Connect(function()Cir.Position,Cir.Radius,Cir.Visible=Cam.ViewportSize/2,O.FOV,O.Active dE()if O.Active and hd then local t=gt()if t then local cf=CFrame.new(Cam.CFrame.Position,t.Position)Cam.CFrame=O.Smooth>1 and Cam.CFrame:Lerp(cf,1/O.Smooth) or cf end end end)
